#!/bin/bash

BASE="~/projetos/flexxo-react-next-js"
README="$BASE/README.md"
AULA03="$BASE/aulas/aula-03-roteamento-link-listas.md"

echo "⚙️  Atualizando README e criando material da Aula 03..."

mkdir -p "$(dirname "$AULA03")"

# ==========================================================
# FUNÇÃO AUXILIAR
# ==========================================================
escrever() {
  echo "$2" >> "$1"
}

# ==========================================================
# 1) NOVO ARQUIVO — AULA 03
# ==========================================================
> "$AULA03"
a() { escrever "$AULA03" "$1"; }

a "# 📘 AULA 03 — Navegação no Next.js: Roteamento por Pastas, Link e Listas"
a ""
a "> Material didático da Escola Flexxo — Polo Caxias do Sul."
a "> Foco: como o Next.js cria páginas a partir de pastas, como navegar entre elas com o componente \`<Link>\` e como renderizar listas com \`.map()\`."
a ""
a "---"
a ""
a "## 🎯 Objetivos da Aula"
a ""
a "- Entender o roteamento por pastas (File-Based Routing) do App Router"
a "- Dominar o componente \`<Link>\` e o conceito de SPA"
a "- Renderizar listas dinâmicas com \`.map()\` e o uso da \`key\`"
a "- Saber onde colocar componentes reutilizáveis no projeto"
a ""
a "---"
a ""
a "## 📋 1. Renderizando Listas com \`.map()\`"
a ""
a "O \`.map()\` transforma **cada item de um array em um elemento JSX**."
a ""
a "\`\`\`jsx"
a "const frutas = ['🍎 Maçã', '🍌 Banana', '🍇 Uva'];"
a ""
a "{frutas.map((fruta) => <li>{fruta}</li>)}"
a "\`\`\`"
a ""
a "### 🔑 A \`key\` é obrigatória"
a ""
a "Cada item precisa de uma \`key\` única para o React identificá-lo."
a ""
a "\`\`\`jsx"
a "{frutas.map((fruta, index) => ("
a "  <li key={index}>{fruta}</li>"
a "))}"
a "\`\`\`"
a ""
a "> ⚠️ Prefira sempre um \`id\` real à \`key={index}\`, principalmente quando a lista pode mudar de ordem ou ter itens removidos."
a ""
a "### 🎬 Exemplo completo — Lista de Tarefas"
a ""
a "\`\`\`jsx"
a "'use client';"
a ""
a "import { useState } from 'react';"
a ""
a "export default function ListaTarefas() {"
a "  const [tarefas, setTarefas] = useState(["
a "    { id: 1, texto: 'Estudar React 📚' },"
a "    { id: 2, texto: 'Tomar café ☕' },"
a "    { id: 3, texto: 'Dar aula 👨‍🏫' },"
a "  ]);"
a ""
a "  function adicionar() {"
a "    const nova = {"
a "      id: Date.now(),"
a "      texto: \`Tarefa \${tarefas.length + 1} ✨\`,"
a "    };"
a "    setTarefas([...tarefas, nova]);"
a "  }"
a ""
a "  return ("
a "    <div style={{ padding: '20px' }}>"
a "      <h2>📋 Minhas Tarefas ({tarefas.length})</h2>"
a "      <ul>"
a "        {tarefas.map((tarefa) => ("
a "          <li key={tarefa.id}>{tarefa.texto}</li>"
a "        ))}"
a "      </ul>"
a "      <button onClick={adicionar}>+ Adicionar tarefa</button>"
a "    </div>"
a "  );"
a "}"
a "\`\`\`"
a ""
a "> 💡 Dica: o par perfeito do \`.map()\` é o \`.filter()\` para remover itens:"
a "> \`setTarefas(tarefas.filter((t) => t.id !== id));\`"
a ""
a "---"
a ""
a "## 📁 2. Roteamento por Pastas (App Router)"
a ""
a "**Regra de ouro:** cada \`page.jsx\` dentro de uma pasta = uma rota (URL)."
a ""
a "\`\`\`"
a "app/"
a "├── page.jsx              →  /              (página inicial)"
a "├── sobre/"
a "│   └── page.jsx          →  /sobre"
a "└── contato/"
a "    └── page.jsx          →  /contato"
a "\`\`\`"
a ""
a "> 📌 O nome da **pasta** vira a URL. O arquivo **sempre** se chama \`page.jsx\` (minúsculo)."
a ""
a "### Exemplo de página"
a ""
a "\`\`\`jsx"
a "// app/sobre/page.jsx"
a "export default function SobrePage() {"
a "  return ("
a "    <main style={{ padding: '30px' }}>"
a "      <h1>📖 Sobre nós</h1>"
a "      <p>Esta página apareceu só por criar a pasta \"sobre\"! 🚀</p>"
a "    </main>"
a "  );"
a "}"
a "\`\`\`"
a ""
a "| Quero a URL... | Crio o arquivo... |"
a "|----------------|-------------------|"
a "| \`/\` | \`app/page.jsx\` |"
a "| \`/sobre\` | \`app/sobre/page.jsx\` |"
a "| \`/contato\` | \`app/contato/page.jsx\` |"
a "| \`/blog/posts\` | \`app/blog/posts/page.jsx\` |"
a ""
a "---"
a ""
a "## 🔗 3. O Componente \`<Link>\`"
a ""
a "### O problema do \`<a href>\` tradicional"
a ""
a "A tag \`<a>\` recarrega o site INTEIRO a cada clique: descarta a página, pede tudo de novo ao servidor e remonta do zero (a tela pisca em branco). É lento."
a ""
a "### A solução: SPA + \`<Link>\`"
a ""
a "Apps Next são **SPAs (Single Page Applications)**: o site carrega uma vez e depois troca apenas o **pedaço** que muda. O \`<Link>\` dá esse comportamento à navegação."
a ""
a "\`\`\`jsx"
a "import Link from 'next/link';"
a ""
a "export default function Menu() {"
a "  return ("
a "    <nav style={{ display: 'flex', gap: '15px' }}>"
a "      <Link href=\"/\">Início</Link>"
a "      <Link href=\"/sobre\">Sobre</Link>"
a "      <Link href=\"/contato\">Contato</Link>"
a "    </nav>"
a "  );"
a "}"
a "\`\`\`"
a ""
a "### \`<a>\` vs \`<Link>\`"
a ""
a "| Critério | \`<a href>\` 🐢 | \`<Link href>\` 🚀 |"
a "|----------|--------------|------------------|"
a "| Recarrega a página? | Sim (pisca) | Não (instantâneo) |"
a "| Velocidade | Lenta | Rápida |"
a "| Mantém o estado do app? | ❌ Perde tudo | ✅ Mantém |"
a "| Pré-carrega a página (prefetch)? | ❌ Não | ✅ Sim |"
a ""
a "### 🔮 Prefetch"
a ""
a "Quando um \`<Link>\` aparece na tela, o Next já baixa a página de fundo. No clique, ela abre na hora. Por isso sites em Next são tão rápidos."
a ""
a "### Recursos extras"
a ""
a "\`\`\`jsx"
a "// Link dinâmico com variável"
a "const id = 42;"
a "<Link href={\`/produto/\${id}\`}>Ver produto</Link>"
a ""
a "// Desligar prefetch (casos específicos)"
a "<Link href=\"/sobre\" prefetch={false}>Sobre</Link>"
a "\`\`\`"
a ""
a "> 🎯 Regra: link **interno** (seu próprio site) → \`<Link>\`. Link **externo** (outro site) → \`<a>\`."
a ""
a "---"
a ""
a "## 🗂️ 4. Onde colocar os componentes"
a ""
a "### Cenário A — Direto na página"
a ""
a "Para um menu de uso único, coloque o \`<Link>\` direto no \`page.jsx\`."
a ""
a "### Cenário B — Componente reutilizável (profissional)"
a ""
a "Crie um arquivo próprio e importe onde precisar:"
a ""
a "\`\`\`jsx"
a "// app/components/Menu.jsx"
a "import Link from 'next/link';"
a ""
a "export default function Menu() {"
a "  return ("
a "    <nav style={{ display: 'flex', gap: '15px' }}>"
a "      <Link href=\"/\">Início</Link>"
a "      <Link href=\"/sobre\">Sobre</Link>"
a "      <Link href=\"/contato\">Contato</Link>"
a "    </nav>"
a "  );"
a "}"
a "\`\`\`"
a ""
a "\`\`\`jsx"
a "// app/page.jsx"
a "import Menu from './components/Menu';"
a ""
a "export default function HomePage() {"
a "  return ("
a "    <main style={{ padding: '30px' }}>"
a "      <Menu />"
a "      <h1>🏠 Página Inicial</h1>"
a "    </main>"
a "  );"
a "}"
a "\`\`\`"
a ""
a "### Estrutura de pastas"
a ""
a "\`\`\`"
a "app/"
a "├── page.jsx                 ← usa o <Menu />"
a "├── components/"
a "│   └── Menu.jsx             ← componente reutilizável"
a "├── sobre/"
a "│   └── page.jsx"
a "└── contato/"
a "    └── page.jsx"
a "\`\`\`"
a ""
a "> ⚠️ Atenção ao caminho do import:"
a "> - De \`app/page.jsx\` → \`'./components/Menu'\`"
a "> - De \`app/sobre/page.jsx\` → \`'../components/Menu'\` (o \`..\` sobe uma pasta)"
a ""
a "| Quero o menu... | Onde coloco o código |"
a "|-----------------|---------------------|"
a "| Só em 1 página | direto no \`page.jsx\` dela |"
a "| Reutilizável em várias | \`components/Menu.jsx\` + importar |"
a "| Em todas automaticamente | \`layout.jsx\` (próxima aula) |"
a ""
a "---"
a ""
a "## 📚 Referências"
a ""
a "- [Next.js — Link Component](https://nextjs.org/docs/app/api-reference/components/link)"
a "- [Next.js — Routing Fundamentals](https://nextjs.org/docs/app/building-your-application/routing)"
a "- [React — Rendering Lists](https://react.dev/learn/rendering-lists)"
a ""
a "---"
a ""
a "*Material didático — Escola Flexxo, Polo Caxias do Sul © 2026*"

# ==========================================================
# 2) ATUALIZA O README — adiciona link da Aula 03
# ==========================================================
if grep -q "aula-03-roteamento-link-listas.md" "$README"; then
  echo "ℹ️  README já referencia a Aula 03 — pulando atualização."
else
  # Substitui a linha "Material da Aula 03 (em breve)" pelo link real
  sed -i 's|📄 Material da Aula 03 \*(em breve)\*|📄 [Material completo da Aula 03](./aulas/aula-03-roteamento-link-listas.md)|' "$README"
  echo "✅ README atualizado com o link da Aula 03."
fi

# ==========================================================
# FINAL
# ==========================================================
echo ""
echo "✅ Aula 03 criada em: $AULA03"
echo "📄 $(wc -l < "$AULA03") linhas"
echo ""
echo "🎉 Tudo pronto! Faça o commit no repositório."

